[flavor]
light = "bluloco-light"
dark  = "bluloco-light"

# [flavor]
# light = "rose-pine-dawn"

# [flavor]
# light = "bluloco-light"
#
# [flavor]
# light = "flexoki-light"
#
# [flavor]
# light = "kanagawa-lotus"
#
# [flavor]
# light = "catppuccin-latte"

