[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml', 'conf']


[[plugins]]
repo  = 'vim-vdebug/vdebug'
if    = 'has("python3") && executable("php")'
on_ft = ['php']
hook_post_source = '''
    let g:vdebug_options= {
    \    "port" : 9000,
    \    "server" : '',
    \    "timeout" : 20,
    \    "on_close" : 'detach',
    \    "break_on_open" : 0,
    \    "ide_key" : 'XDEBUG_VIM',
    \    "path_maps" : {},
    \    "debug_window_level" : 0,
    \    "debug_file_level" : 0,
    \    "debug_file" : "",
    \    "watch_window_style" : 'expanded',
    \    "marker_default" : '⬦',
    \    "marker_closed_tree" : '▸',
    \    "marker_open_tree" : '▾'
    \}
'''


[[plugins]]
repo  = 'phpactor/phpactor'
if    = 'executable("php")'
on_ft = ['php']
build = 'composer install'
hook_add = '''
    let g:phpactorBranch               = 'develop'
    let g:phpactorOmniAutoClassImport  = v:true
    let g:phpactorCompletionIgnoreCase = 0


    function! DefinitionJumpWithPhpactor()
        belowright split
        call phpactor#GotoDefinition()
    endfunction

    aug enablePhpactorKeyBindings
        au!
        " Include use statement
        nmap <silent><Space>pu           :<C-u>call phpactor#UseAdd()<CR>
        " Invoke the context menu
        nmap <silent><Space>pcm          :<C-u>call phpactor#ContextMenu()<CR>
        " Invoke the navigation menu
        nmap <silent><Space>pn           :<C-u>call phpactor#Navigate()<CR>
        " Goto definition of class or class member under the cursor
        nmap <silent><Space>p<C-]>       :<C-u>call phpactor#GotoDefinition()<CR>
        " Goto definition of class or class member under the cursor
        nmap <silent><Space>p<C-w><C-]>  :<C-u>call DefinitionJumpWithPhpactor()<CR>
        " Transform the classes in the current file
        nmap <silent><Space>pt           :<C-u>call phpactor#Transform()<CR>
        " Generate a new class (replacing the current file)
        nmap <silent><Space>pcn          :<C-u>call phpactor#ClassNew()<CR>
        "
        nmap <silent><Space>pcf          :<C-u>call phpactor#CopyFile()<CR>

        nmap <silent><Space>pmf          :<C-u>call phpactor#MoveFile()<CR>
        " Extract expression (normal mode)
        nmap <silent><Space>pee          :<C-u>call phpactor#ExtractExpression(v:false)<CR>
        " show Full namespace of class under cursor
        nmap <silent><Space>ph           :<C-u>call phpactor#Hover()<CR>
        " Find references
        nmap <silent><Space>pfr          :<C-u>call phpactor#FindReferences()<CR>

        " Extract expression from selection
        vmap <silent><Space>pee          :<C-u>call phpactor#ExtractExpression(v:true)<CR>
        " Extract method from selection
        vmap <silent><Space>pem          :<C-u>call phpactor#ExtractMethod()<CR>
    aug END
'''


[[plugins]]
repo  = 'phpactor/ncm2-phpactor'
if    = 'executable("php")'
on_ft = ['php']
on_i  = 1


[[plugins]]
repo     = 'Shougo/denite.nvim'
on_cmd   = ['Denite', 'DeniteBufferDir', 'DeniteProjectDir', 'DeniteCursorWord']
if       = 'has("python3")'
hook_add = '''
    aug enableDeniteKeyMap
        au!
        au VimEnter * nested nnoremap <silent><Space>mm  :<C-u>Denite -mode=normal menu<CR>
        au VimEnter * nested nnoremap <silent><Space>ml  :<C-u>Denite -mode=normal menu:laravel<CR>
        au VimEnter * nested nnoremap <silent><Space>mg  :<C-u>Denite -mode=normal menu:grep<CR>

        au VimEnter * nested nnoremap <silent><Space>uR  :<C-u>Denite -smartcase -mode=normal register<CR>
        au VimEnter * nested nnoremap <silent><Space>uy  :<C-u>Denite -smartcase -mode=normal neoyank<CR>
        au VimEnter * nested nnoremap <silent><Space>uh  :<C-u>Denite -smartcase help<CR>
        au VimEnter * nested nnoremap <silent><Space>ub  :<C-u>Denite -default-action=switch -smartcase -mode=normal buffer<CR>
        au VimEnter * nested nnoremap <silent><Space>uj  :<C-u>Denite -default-action=open   -smartcase -mode=normal -auto-preview jump<CR>
        au VimEnter * nested nnoremap <silent><Space>uM  :<C-u>Denite -default-action=open   -smartcase -mode=normal -auto-preview mark<CR>

        au VimEnter * nested nnoremap <silent><Space>ul  :<C-u>Denite           -no-empty -auto-highlight -smartcase -mode=insert -auto-resize line<CR>
        au VimEnter * nested nnoremap <silent><Space>*   :<C-u>DeniteCursorWord -no-empty -auto-highlight -smartcase -mode=normal line<CR>

        au VimEnter * nested nnoremap <silent><Space>q:  :<C-u>Denite -mode=normal -smartcase -reversed command_history<CR>

        " ファイル関係
        au VimEnter * nested nnoremap <silent><Space>uf  :<C-u>DeniteBufferDir  -no-empty -smartcase -mode=normal file<CR>
        au VimEnter * nested nnoremap <silent><Space>uc  :<C-u>DeniteProjectDir -no-empty -smartcase -mode=normal file<CR>
        au VimEnter * nested nnoremap <silent><Space>um  :<C-u>Denite           -no-empty -smartcase -mode=normal file_mru<CR>
        au VimEnter * nested nnoremap <silent><Space>ua  :<C-u>Denite           -no-empty -smartcase -mode=normal file/rec<CR>
        au VimEnter * nested nnoremap <silent><Space>ug  :<C-u>DeniteProjectDir -no-empty -smartcase -mode=normal file/git<CR>

        " git
        au VimEnter * nested nnoremap <silent><Space>gg  :<C-u>Denite -no-empty -smartcase -mode=normal -auto-preview   grep/git<CR>
        au VimEnter * nested nnoremap <silent><Space>gG  :<C-u>Denite -no-empty -smartcase -mode=normal -auto-preview   igrep/git<CR>
        au VimEnter * nested nnoremap <silent><Space>gl  :<C-u>Denite -no-empty -smartcase -mode=normal -auto-preview   gitlog<CR>
        au VimEnter * nested nnoremap <silent><Space>gs  :<C-u>Denite -no-empty -smartcase -mode=normal -auto-preview   gitstatus<CR>
        au VimEnter * nested nnoremap <silent><Space>gb  :<C-u>Denite -no-empty -smartcase -mode=normal -auto-preview   gitbranch<CR>

        " 検索結果の再表示と移動
        au VimEnter * nested nnoremap <silent><Space>ur  :<C-u>Denite -resume -no-empty<CR>
        au VimEnter * nested nnoremap <silent>[u         :<C-u>Denite -resume -no-empty -select=-1 -immediately<CR>
        au VimEnter * nested nnoremap <silent>]u         :<C-u>Denite -resume -no-empty -select=+1 -immediately<CR>
    aug END
'''
hook_post_source = '''

    " keymap

    call denite#custom#map(
                \ 'insert', '<C-n>', '<denite:move_to_next_line>',      'noremap'
                \)
    call denite#custom#map(
                \ 'insert', '<C-p>', '<denite:move_to_previous_line>',  'noremap'
                \)
    call denite#custom#map(
                \ 'insert', '<C-s>', '<denite:do_action:splitswitch>',  'noremap'
                \)
    call denite#custom#map(
                \ 'insert', '<C-v>', '<denite:do_action:vsplitswitch>', 'noremap'
                \)
    call denite#custom#map(
                \ 'insert', '<C-t>', '<denite:do_action:tabswitch>',    'noremap'
                \)
    call denite#custom#map(
                \ 'normal', 'M',     '<denite:move_to_middle>',         'noremap'
                \)
    call denite#custom#map(
                \ 'normal', 's',     '<denite:do_action:splitswitch>',  'noremap'
                \)
    call denite#custom#map(
                \ 'normal', 'v',     '<denite:do_action:vsplitswitch>', 'noremap'
                \)

    " file/git

    call denite#custom#alias('source', 'file/git', 'file/rec')
    call denite#custom#var(
                \ 'file/git', 'command',
                \ ['git', 'ls-files', '-co', '--exclude-standard']
                \)

    " grep/git

    call denite#custom#alias('source', 'grep/git', 'grep')
    call denite#custom#var('grep/git', 'command',
                \ ['git', 'grep']
                \)
    call denite#custom#var('grep/git', 'recursive_opts', [])
    call denite#custom#var('grep/git', 'pattern_opt',    [])
    call denite#custom#var('grep/git', 'default_opts',   ['-nH'])

    " grep

    call denite#custom#var('grep', 'default_opts',
                \ [
                \   '-nH',
                \   '--exclude-dir=.git',
                \   '--exclude-dir=storage',
                \   '--exclude=tags',
                \   '--exclude=GPATH',
                \   '--exclude=GTAGS',
                \   '--exclude=GRTAGS',
                \   '--exclude=_ide_helper.php',
                \   '--exclude=query',
                \ ]
                \)
    call denite#custom#var('grep', 'patten_opt', ['-E'])

    " grep/git ignore case

    call denite#custom#alias('source', 'igrep/git', 'grep')
    call denite#custom#var('igrep/git', 'command',
                \ ['git', 'grep']
                \)
    call denite#custom#var('igrep/git', 'recursive_opts', [])
    call denite#custom#var('igrep/git', 'pattern_opt',    [])
    call denite#custom#var('igrep/git', 'default_opts',   ['-inH'])


    for source in ['jump', 'register', 'neoyank', 'mark', 'line', 'file_mru', 'grep', 'grep/git', 'igrep/git', 'gitlog', 'gitstatus', 'gitbranch']
        call denite#custom#source(source, 'matchers', ['matcher/substring'])
    endfor


    for source in ['buffer', 'file', 'file/rec', 'file/git']
        call denite#custom#source(source, 'matchers', ['matcher/substring'])
        call denite#custom#source(source, 'sorters',  ['sorter/word'])
    endfor


    " prompt

    call denite#custom#option('default', 'prompt', '$')


    let s:menus = {}

    let s:menus.laravel = {
                \ 'description' : 'Laravel Operations'
                \ }
    let s:menus.laravel.command_candidates = [
                \ ['Open Controller', 'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Controller$ -path=app/Http/Controllers         file/rec'],
                \ ['Open Domain',     'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Domain$     -path=app/Domains                  file/rec'],
                \ ['Open Service',    'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Service$    -path=app/Models/Service           file/rec'],
                \ ['Open Dao',        'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Dao$        -path=app/Models/Dao               file/rec'],
                \ ['Open Model',      'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Model$      -path=app/Models                   file/rec'],
                \ ['Open Middleware', 'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Middleware$ -path=app/Http/Middleware          file/rec'],
                \ ['Open Request',    'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Request$    -path=app/Http/Requests            file/rec'],
                \ ['Open View',       'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ View$       -path=resources/views              file/rec'],
                \ ['Open Test',       'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Test$       -path=tests                        file/rec'],
                \ ['Open Illuminate', 'Denite -default-action=switch -smartcase -mode=normal -prompt=Open\ Illuminate$ -path=vendor/laravel/framework/src file/rec'],
                \ ['Document grep',   'Denite -no-empty -default-action=split -smartcase -mode=normal -auto-preview -vertical-preview grep:~/.vim/ref/laravel.doc/translation-ja'],
                \ ['Document titles', 'Denite -no-empty -default-action=split -smartcase -mode=normal -auto-preview -vertical-preview file/rec:~/.vim/ref/laravel.doc/translation-ja'],
                \]

    let s:menus.grep = {
                \ 'description' : 'Grep Operations'
                \ }
    let s:menus.grep.command_candidates = [
                \ ['Grep',                       'Denite -no-empty -smartcase -mode=normal -auto-preview   grep'],
                \ ['Grep with directory config', 'Denite -no-empty -smartcase -mode=normal -auto-preview   grep::!'],
                \]


    call denite#custom#var('menu', 'menus', s:menus)

'''
depends  = ['neoyank.vim', 'neomru.vim', 'denite-git']


[[plugins]]
repo = 'Shougo/neomru.vim'


[[plugins]]
repo     = 'Shougo/neoyank.vim'


[[plugins]]
repo  = 'rhysd/vim-textobj-ruby'
on_ft = ['ruby', 'eruby']
hook_source = '''
    let g:textobj_ruby_more_mappings = 1
'''


[[plugins]]
repo  = 'tpope/vim-endwise'
on_ft = ['ruby', 'eruby']


[[plugins]]
repo  = 'davidhalter/jedi'
on_ft = ['python']


[[plugins]]
repo  = 'ncm2/ncm2-jedi'
on_ft = ['python']


[[plugins]]
repo     = 'neoclide/denite-git'

