[[plugins]]
repo = 'sjl/badwolf'


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'felipesousa/rupza'


[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'GGalizzi/cake-vim'


[[plugins]]
repo = 'sickill/vim-monokai'


[[plugins]]
repo = 'vim-scripts/phd'


[[plugins]]
repo = 'NLKNguyen/papercolor-theme'


[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    let g:gruvbox_contrast_light = "medium"
    let g:gruvbox_contrast_dark  = "medium"
    let g:gruvbox_number_column  = "bg1"
    let g:gruvbox_italic         = 1
'''


[[plugins]]
repo = 'Lokaltog/vim-distinguished'


[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
    let g:ayucolor="mirage"  " light, mirage, dark
'''


[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
    let g:one_allow_italics = 1
'''


[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
    let g:solarized_term_italics    = 1
    let g:solarized_extra_hi_groups = 1
'''


