[[plugins]]
repo     = 'sjl/badwolf'
hook_add = '''
    let g:badwolf_darkgutter = 1
'''


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'felipesousa/rupza'


[[plugins]]
repo = 'GGalizzi/cake-vim'


[[plugins]]
repo = 'sickill/vim-monokai'


[[plugins]]
repo = 'vim-scripts/phd'


[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
hook_add = '''
    let g:PaperColor_Theme_Options = {
    \   'theme': {
    \     'default': {
    \       'allow_bold':   1,
    \       'allow_italic': 1
    \     }
    \   }
    \ }
'''


[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    let g:gruvbox_number_column  = "bg1"
    let g:gruvbox_italic         = 1
'''


[[plugins]]
repo = 'Lokaltog/vim-distinguished'


[[plugins]]
repo = 'ayu-theme/ayu-vim'


[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
    let g:one_allow_italics = 1
'''


[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
    let g:solarized_term_italics    = 1
    let g:solarized_extra_hi_groups = 1
'''


[[plugins]]
repo = 'cocopon/iceberg.vim'


[[plugins]]
repo = 'jeetsukumaran/vim-nefertiti'


[[plugins]]
repo = 'vim-scripts/paroton'


[[plugins]]
repo = 'vim-scripts/pyte'

