[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja
'''


[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
    let g:ref_phpmanual_path = $HOME . '/.vim/ref/php-chunked-xhtml'
    let g:ref_detect_filetype = {
    \       'php' : 'phpmanual'
    \}

    let g:ref_source_webdict_sites = {
    \   'wiki': {
    \     'url': 'http://ja.wikipedia.org/wiki/%s',
    \   },
    \ }


    "出力に対するフィルタ。最初の数行を削除

    " function! g:ref_source_webdict_sites.je.filter(output)
    "   return join(split(a:output, "\n")[15 :], "\n")
    " endfunction

    " nmap <Leader>wiki :<C-u>Ref webdict wiki<Space>
'''


[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_sign_error = '!!'
    " let g:ale_php_phpcs_use_global = 1
    " let g:ale_php_phpcs_standard = 'PSR2'
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'osyo-manga/vim-precious'


[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    aug enableNERDTree
        au!
        au VimEnter * nested noremap <Space>nt :NERDTreeToggle<Return>
        au VimEnter * nested noremap <Space>nc :NERDTreeCWD<Return>
    aug END
'''


[[plugins]]
repo = 'tomtom/tcomment_vim'


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
    " let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline_theme = 'light'
    " let g:airline#extensions#default#layout = [
    "             \ ['a', 'c'],
    "             \ ['x', 'y', 'z']
    "             \ ]
'''
depends = ['vim-airline/vim-airline-themes']


[[plugins]]
repo = 'vim-airline/vim-airline-themes'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


[[plugins]]
repo = 'tpope/vim-dispatch'


[[plugins]]
repo = 'Shougo/neomru.vim'


[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
    map  <silent> ]w <Plug>CamelCaseMotion_w
    map  <silent> ]b <Plug>CamelCaseMotion_b
    map  <silent> ]e <Plug>CamelCaseMotion_e
    omap <silent> ]iw <Plug>CamelCaseMotion_iw
    vmap <silent> ]iw <Plug>CamelCaseMotion_iw
    omap <silent> ]ib <Plug>CamelCaseMotion_ib
    vmap <silent> ]ib <Plug>CamelCaseMotion_ib
    omap <silent> ]ie <Plug>CamelCaseMotion_ie
    vmap <silent> ]ie <Plug>CamelCaseMotion_ie
'''


[[plugins]]
repo = 'kana/vim-textobj-user'


[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    let g:unite_split_rule = 'rightbelow'
    let g:unite_winwidth = 40
    let g:unite_source_history_yank_enable = 1
    let g:unite_source_file_mru_limit = 1000

    aug enableUniteKeyBindings
        au!
        au VimEnter * nested nnoremap <silent> <Space>ut  :<C-u>Unite tab<CR>
        au VimEnter * nested nnoremap <silent> <Space>ub  :<C-u>Unite buffer<CR>
        au VimEnter * nested nnoremap <silent> <Space>ur  :<C-u>Unite -buffer-name=register register<CR>
        au VimEnter * nested nnoremap <silent> <Space>uj  :<C-u>Unite jump<CR>
        " ファイル関係
        au VimEnter * nested nnoremap <silent> <Space>um  :<C-u>Unite file_mru<CR>
        au VimEnter * nested nnoremap <silent> <Space>ug  :<C-u>Unite -buffer-name=files file_rec/git<CR>
        au VimEnter * nested nnoremap <silent> <Space>ua  :<C-u>Unite -buffer-name=files file_rec<CR>
        au VimEnter * nested nnoremap <silent> <Space>uf  :<C-u>UniteWithBufferDir  -buffer-name=files file<CR>
        au VimEnter * nested nnoremap <silent> <Space>uc  :<C-u>UniteWithCurrentDir -buffer-name=files file<CR>
    aug END
'''


[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
    aug enableOutline
        au!
        au VimEnter * nested nnoremap <Space>uo :<C-u>Unite -vertical outline<CR>
    aug END
'''


[[plugins]]
repo = 'Shougo/neoyank.vim'
hook_add = '''
    aug enableNeoyank
        au!
        au VimEnter * nested noremap <Space>uy :<C-u>Unite history/yank<CR>
    aug END
'''


[[plugins]]
repo = 'hewes/unite-gtags'
hook_add = '''
    nnoremap <silent> <Space>gc :<C-u>Unite gtags/context<CR>
    nnoremap <silent> <Space>gf :<C-u>Unite gtags/file<CR>
    nnoremap <silent> <Space>gd :<C-u>Unite gtags/def<CR>
    nnoremap <silent> <Space>gr :<C-u>Unite gtags/ref<CR>
'''



[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    " let g:indentLine_setColors = 0
'''


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let quickrun_config = {
    \   "_" : {
    \       "outputter/buffer/close_on_empty" : 1,
    \       "runner" : "vimproc"
    \   }
    \}
    aug enableQuickRun
        au!
        au VimEnter * nested noremap <Space>qr :<C-u>QuickRun<CR>
    aug END
'''


[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'


[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
'''


[[plugins]]
repo = 'itchyny/thumbnail.vim'
hook_add = '''
    aug enableThumbnail
        au!
        au VimEnter * nested noremap <Space>th :<C-u>Thumbnail<CR>
    aug END
'''


[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = '''
    let g:eskk#directory = "~/.skk"
    let g:eskk#dictionary = { 'path': "~/.skk-jisyo", 'sorted': 0, 'encoding': 'utf-8', }
    let g:eskk#large_dictionary = { 'path': "~/.skk/SKK-JISYO.L", 'sorted': 1, 'encoding': 'euc-jp', }
    set imdisable
    let g:eskk#enable_completion = 1
    let g:eskk#server = {
    \   'host': 'localhost',
    \   'port': 55100,
    \}
'''


[[plugins]]
repo = 'jwalton512/vim-blade'
hook_source = '''
    syntax on
    let g:blade_custom_directives = ['datetime', 'namespaced::directive']
    let g:blade_custom_directives_pairs = {'cache': 'endcache'}
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'


[[plugins]]
repo = 'aklt/plantuml-syntax'


[[plugins]]
repo = 'mattn/emmet-vim'


[[plugins]]
repo = 'othree/html5.vim'


# colorschemes


[[plugins]]
repo = 'sjl/badwolf'


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'Dru89/vim-adventurous'


[[plugins]]
repo = 'Heorhiy/VisualStudioDark.vim'


[[plugins]]
repo = 'felipesousa/rupza'


[[plugins]]
repo = 'jalvesaq/southernlights'


[[plugins]]
repo = 'anoike/vim-moneyforward'


[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'GGalizzi/cake-vim'


[[plugins]]
repo = 'reedes/vim-colors-pencil'
hook_add = '''
    let g:pencil_higher_contrast_ui = 1
    let g:pencil_neutral_code_bg    = 1
    let g:pencil_gutter_color       = 1
'''


[[plugins]]
repo = 'freeo/vim-kalisi'


[[plugins]]
repo = 'romainl/Apprentice'


[[plugins]]
repo = 'AlessandroYorba/Despacio'


[[plugins]]
repo = 'junegunn/seoul256.vim'


[[plugins]]
repo = 'fneu/breezy'


[[plugins]]
repo = 'sickill/vim-monokai'


[[plugins]]
repo = 'vim-scripts/phd'


[[plugins]]
repo = 'vim-scripts/summerfruit256.vim'


[[plugins]]
repo = 'cocopon/iceberg.vim'


[[plugins]]
repo = 'NLKNguyen/papercolor-theme'


[[plugins]]
repo = 'nice/sweater'


[[plugins]]
repo = 'vim-scripts/Blueshift'


[[plugins]]
repo = 'noahfrederick/vim-hemisu'


[[plugins]]
repo = 'morhetz/gruvbox'


[[plugins]]
repo = 'Lokaltog/vim-distinguished'


